# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"url2api": "00_wp2md.ipynb",
         "WP": "00_wp2md.ipynb",
         "wp2md": "00_wp2md.ipynb"}

modules = ["wp2md.py"]

doc_url = "https://outerbounds.github.io/wp2md/"

git_url = "https://github.com/outerbounds/wp2md/tree/master/"

def custom_doc_links(name): return None
